# Generated by Django 3.1 on 2020-09-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nairobi_hospitals_api', '0002_auto_20200908_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nairobihealthfacilities',
            name='distance',
        ),
    ]
